### Follow rest requests to test some routes
### Required: install REST Client extension

### 1. Create a new user
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "name": "Pedro",
  "lastname": "Camargo",
  "email": "pedro@mail.com",
  "password": "senhaSegura123"
}

### 2. Login with credentials
# @name login_with_credentials
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "pedro@mail.com",
  "password": "senhaSegura123"
}

### References
@token = {{login_with_credentials.response.body.data.token}}

### 4. Get student data
GET http://localhost:3000/api/me/2
Content-Type: application/json
Authorization: Bearer {{token}}


### 5. Update student data
PUT http://localhost:3000/api/me/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Felipe"
}

### 6. Create simulation
POST http://localhost:3000/api/simulations
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "total_amount": 3000,
  "total_installments": 10,
  "interest_per_month": 0.05
}

### 7. List simulations
GET http://localhost:3000/api/simulations
Authorization: Bearer {{token}}