### 1. Registrar novo usuário
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "name": "novo",
  "lastname": "usuario",
  "email": "novo@exemplo.com",
  "password": "senhaSegura123"
}

### 2. Login com credenciais válidas
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "novo@exemplo.com",
  "password": "senhaSegura123"
}

### 3. Login com credenciais inválidas (TESTE DE ERRO)
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "ana2@exemplo.com",
  "password": "senhaErrada"
}

###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJub3ZvQGV4ZW1wbG8uY29tIiwiaWF0IjoxNzQ0MjQwNDczLCJleHAiOjE3NDQyNDQwNzN9.K3AOlTLyOVpNK9S6khxEtXXYfXRyhq2Id-aoyyh5L2Y

### 4. Get student data
GET http://localhost:3000/api/me/2
Content-Type: application/json
Authorization: Bearer {{token}}


### 5. Update student data
PUT http://localhost:3000/api/me/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "novo 2"
}

### 6. Create simulation
POST http://localhost:3000/api/simulations
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "total_amount": 1000,
  "total_installments": 10,
  "interest_per_month": 0.05
}

### 7. List simulations
GET http://localhost:3000/api/simulations
Authorization: Bearer {{token}}