### 1. Registrar novo usuário
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "name": "Ana",
  "lastname": "Silva",
  "email": "ana2@exemplo.com",
  "password": "senhaSegura123"
}

### 2. Login com credenciais válidas
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "ana22@exemplo.com",
  "password": "senhaSegura123"
}

### 3. Login com credenciais inválidas (TESTE DE ERRO)
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "ana2@exemplo.com",
  "password": "senhaErrada"
}

###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhbmFAZXhlbXBsby5jb20iLCJpYXQiOjE3NDQxNTc3OTIsImV4cCI6MTc0NDE2MTM5Mn0.uehOEcnUD3_triviO62S1tJCiRs9u5qs1O_mGW6JWrM

### 4. Get student data
GET http://localhost:3000/api/me/1
Content-Type: application/json
Authorization: Bearer {{token}}


### 5. Update student data
PUT http://localhost:3000/api/me/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Ana Silva 3"
}

### 6. Create simulation
POST http://localhost:3000/api/simulations
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "total_amount": 1000,
  "total_installments": 5,
  "interest_per_month": 0.02
}

### 7. List simulations
GET http://localhost:3000/api/simulations
Authorization: Bearer {{token}}